Other endpoints required by Hasura
couchbaselabs/Hasura-Connector pull request #31
Opened 2022-12-06 13:48 UTC by yoanesp

Add health check endpoint
- Include a health check of the cluster connection
Add metrics endpoint
Add raw query and explain endpoints

close #8, #10

2022-12-07 00:06 UTC, ejscribner approved these changes

2022-12-08 19:21 UTC, biozal requested changes

2022-12-08 19:21 UTC, biozal commented on src/index.ts
>    buckets: prometheus.exponentialBuckets(0.0001, 10, 8),
Can we please put some comments in here to explain why we are setting the exponential buckets to 0.0001, 10, and 8.  These all look like magic ints to me where they are magical, and I'm not sure why the values are set to them.

2022-12-08 19:21 UTC, biozal commented on src/index.ts
> +    end();
If the queryData function throws an exception, what happens?  You are always assuming a QueryResponse or ErrorResponse is returned from queryData function, but I see nothing that checks to see if the bucket = cluster.bucket(config.bucket) throws an exception.  We always assume the bucket worked, but there are many reasons that the bucket could not return at all like the configuration is wrong, the cluster is down, or it can't look up the DNS name (because it's always DNS, right?).   This code seems to only have a happy path and not a path if the bucket doesn't return properly thus cascading up to the server.post that doesn't handle it either.

2022-12-08 19:21 UTC, biozal commented on src/index.ts
> +    const result = await cb.cluster.query(n1ql_query);
What if clsuter.query bombs out because you can't get to it and throws a timeout error or something else?  I don't see a path for this, and if anything, we assume results will always have a rows property/collection.

2022-12-15 16:17 UTC, biozal approved these changes

2022-12-15 16:17 UTC, merged