feat: update schema component
couchbaselabs/Hasura-Connector pull request #7
Opened 2022-11-15 16:34 UTC by yoanesp

- parse schema from bucket, scope and collection
 - update config
 - update query 
  
 close #6

2022-11-15 20:19 UTC, biozal requested changes
More feedback:

In general, method signatures should match the documentation.  Examples of breaking this rule include:
- In query.ts lines, 353 - 354 parameters don't match the function signature.  
- In query.ts some functions have documentation of parameters and some don't.  We should document every function.  

In general, do not leave code comments out in the codebase.  Here are some examples:

- In query.ts lines 53 - 61 are commented out with no idea why they are still in the code.  
- In query.ts lines 90 - 95 are commented out in the switch statement and you are just throwing back an error.
- In query.ts lines 224 - 260 are commented out and no idea why.
- In query.ts lines 282 - 283 are commented out.
- In query.ts lines 359 - 366 are commented out.
- In query.ts lines 445 - 490 are commented out and not sure if this is documentation or not because trying to understand how it relates to the code below it.  

This is co-reviewed by @ejscribner

2022-11-24 02:23 UTC, yoanesp commented
> More feedback:
> 
> In general, method signatures should match the documentation. Examples of breaking this rule include:
> 
> * In query.ts lines, 353 - 354 parameters don't match the function signature.
> * In query.ts some functions have documentation of parameters and some don't.  We should document every function.
> 
> In general, do not leave code comments out in the codebase. Here are some examples:
> 
> * In query.ts lines 53 - 61 are commented out with no idea why they are still in the code.
> * In query.ts lines 90 - 95 are commented out in the switch statement and you are just throwing back an error.
> * In query.ts lines 224 - 260 are commented out and no idea why.
> * In query.ts lines 282 - 283 are commented out.
> * In query.ts lines 359 - 366 are commented out.
> * In query.ts lines 445 - 490 are commented out and not sure if this is documentation or not because trying to understand how it relates to the code below it.
> 
> This is co-reviewed by @ejscribner

2022-12-01 13:31 UTC, yoanesp commented on src/schema.ts
> -/*const DocumentInfoSchema = new Schema({
👍

2022-12-01 13:33 UTC, yoanesp commented on src/query.ts
>     /*const joinArray = joinInfo
No, I don't

2022-12-01 13:35 UTC, yoanesp commented on src/config.ts
> +  scope: string | '_defualt',
I updated this

2022-12-01 16:10 UTC, biozal approved these changes

2022-12-01 17:28 UTC, ejscribner approved these changes

2022-12-01 18:41 UTC, merged